# Generated by Django 5.1.7 on 2025-07-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('Codprodu', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(max_length=30)),
                ('Precio', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('Desc', models.TextField()),
                ('Imagen', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
    ]
